spring:
  main:
    allow-bean-definition-overriding: true
  # 데이터 소스 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 작성 필요
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  # JPA 설정
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
    hibernate:
      ddl-auto: none
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        default_batch_fetch_size: 100
        jdbc.batch_size: 1000
        order_inserts: true
        order_updates: true
        format_sql: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USER_NAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          # auth-code-expiration-millis : 유효시간 5 * 60 * 1000 = 5분
    auth-code-expiration-millis: 300000
  jwt:
    header: Authorization
    secret: TWlzdGVySmVycnkxddaswecasfwevcavaswegbdsfehfwevwvqwfvfwegrehsdfas2bwdvssddMjNzZW9jaGFlNTIza3RzMzIyMGRhaW16emFuZwdvvdxajdjrtiskxvsjzkwkf==
    # 30 * 60 * 1000 = 30분
    access-token-expiration-time: 1800000
    # 30 * 24 * 60 * 60 * 1000 = 30일
    refresh-token-expiration-time: 2592000000
  data:
    rest:
      default-page-size: 10

